server:
  port: 8011
spring:
  datasource:
      url: jdbc:mysql://localhost:3306/studyplatform?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
      username: root
      password: 111111
      driver-class-name: com.mysql.jdbc.Driver
