spring:
  redis:
    # ??
    host: 172.29.2.119
    # ??????6379
    port: 6379
    # ??
    password:
    # ??????
    timeout: 10s
    lettuce:
      pool:
# 连接池最大连接数（使用负值表示没有限制）
# 连接池最大阻塞等待时间（使用负值表示没有限制）
# 连接池中的最大空闲连接
# 连接池中的最小空闲连接
        max-active: 20
        max-wait: -1ms
        max-idle: 10
        min-idle: 0

server:
  port: 8011
