server:
  port: 8011
spring:
  datasource:
      url: jdbc:mysql://localhost:3306/studyplatform?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
      username: root
      password: 111111
      driver-class-name: com.mysql.jdbc.Driver
  security:
    user:
      name: admin
      password: 123456
mybatis-plus:
  global-config:
    db-config:
      id-type: id_worker
      field-strategy: not_empty
      #???????????
      column-underline: true
      #??????????
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: mysql
    refresh: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  mapper-locations: classpath*:mapper/**/*.xml
token:
    # ???????
    header: Authorization
    # ????
    secret: abcdefghijklmnopqrstuvwxyz
    # ????????30???
    expireTime: 30
    expire-time: 600
    key: studyplatform